test update.

diff --git a/.github/workflows/build-wheels-cuda-linux.yaml b/.github/workflows/build-wheels-cuda-linux.yaml
--- a/.github/workflows/build-wheels-cuda-linux.yaml
+++ b/.github/workflows/build-wheels-cuda-linux.yaml
@@ -81,32 +81,31 @@ jobs:
           echo "----------------------"
           which nvcc || echo "nvcc not found"
           nvcc --version || echo "nvcc command failed"
-          nvidia-smi || echo "nvidia-smi command failed"
+          # nvidia-smi || echo "nvidia-smi command failed"
           echo "CUDA Home: $env:CUDA_HOME"
           echo "LD_LIBRARY_PATH: $env:LD_LIBRARY_PATH"
-          echo "PATH: $env:PATH"
 
-      # - name: Build Wheel
-      #   run: |
-      #     $cudaVersion = $env:CUDAVER.Remove($env:CUDAVER.LastIndexOf('.')).Replace('.','')
-      #     $env:CUDA_PATH = $env:CONDA_PREFIX
-      #     $env:CUDA_HOME = $env:CONDA_PREFIX
-      #     $env:CUDA_TOOLKIT_ROOT_DIR = $env:CONDA_PREFIX
-      #     $env:LD_LIBRARY_PATH = $env:CONDA_PREFIX + '/lib:' + $env:LD_LIBRARY_PATH
-      #     $env:VERBOSE = '1'
+      - name: Build Wheel
+        run: |
+          $cudaVersion = $env:CUDAVER.Remove($env:CUDAVER.LastIndexOf('.')).Replace('.','')
+          $env:CUDA_PATH = $env:CONDA_PREFIX
+          $env:CUDA_HOME = $env:CONDA_PREFIX
+          $env:CUDA_TOOLKIT_ROOT_DIR = $env:CONDA_PREFIX
+          $env:LD_LIBRARY_PATH = $env:CONDA_PREFIX + '/lib:' + $env:LD_LIBRARY_PATH
+          $env:VERBOSE = '1'
 
-      #     $env:CMAKE_BUILD_PARALLEL_LEVEL = $(nproc)
-      #     $env:CMAKE_ARGS = '-DSD_CUDA=ON -DGGML_CUDA=ON -DCMAKE_CUDA_ARCHITECTURES=all'
-      #     $env:CMAKE_ARGS = $env:CMAKE_ARGS + ' -DGGML_CUDA_FORCE_MMQ=ON -DGGML_AVX2=OFF -DGGML_FMA=OFF -DGGML_F16C=OFF'
+          $env:CMAKE_BUILD_PARALLEL_LEVEL = $(nproc)
+          $env:CMAKE_ARGS = '-DSD_CUDA=ON -DGGML_CUDA=ON -DCMAKE_CUDA_ARCHITECTURES=all'
+          $env:CMAKE_ARGS = $env:CMAKE_ARGS + ' -DGGML_CUDA_FORCE_MMQ=ON -DGGML_AVX2=OFF -DGGML_FMA=OFF -DGGML_F16C=OFF'
 
-      #     python -m build --wheel
-      #     # write the build tag to the output
-      #     Write-Output "CUDA_VERSION=$cudaVersion" >> $env:GITHUB_ENV
+          python -m build --wheel
+          # write the build tag to the output
+          Write-Output "CUDA_VERSION=$cudaVersion" >> $env:GITHUB_ENV
 
-      # - uses: softprops/action-gh-release@v2
-      #   with:
-      #     files: dist/*
-      #     # Set tag_name to <tag>-cu<cuda_version>
-      #     tag_name: ${{ github.ref_name }}-cu${{ env.CUDA_VERSION }}
-      #   env:
-      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      - uses: softprops/action-gh-release@v2
+        with:
+          files: dist/*
+          # Set tag_name to <tag>-cu<cuda_version>
+          tag_name: ${{ github.ref_name }}-cu${{ env.CUDA_VERSION }}
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
